### ISSUE TITLE
Color wheel does not show brightness on open

### ISSUE THREAD

**Issue by jpatena** [EyreFree/EFColorPicker#12]
It's related to issue #5. When opening a color that's already been set, the color wheel view doesn't include the brightness. Very noticeable when you set the color to black, tap done, then reopen.
<img width="1092" alt="color wheel brightness on open defect" src="https://user-images.githubusercontent.com/5523862/45055525-e7525f00-b044-11e8-9372-22073e69d705.png">

**Comment by EyreFree** [comment]
Thanks for your work, this will be included in the next release.
