### ISSUE TITLE
New iOS 13 popover style doesn't play well with the Color Wheel

### ISSUE THREAD

**Issue by ebarellar** [EyreFree/EFColorPicker#25]
**Issue Description**
If presenting the Controller as a popover (as in the example provided in the README) the new presentation style introduced for iPhones in iOS 13.0 doesn't allow to drag inside the color wheel without the dismiss gesture of the popover being activated

This is easily fixed with the extension provided, but it would be a cool thing if the controller already expected the possibility this behavior

```swift
extension EFColorWheelView{
    override public func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {
        if gestureRecognizer is UIPanGestureRecognizer{
            if let hsbView = self.superview as? EFHSBView{
                return !hsbView.isTouched
            }
        }
        return true
    }
}
```

I don't know what the proper "fix" might be, but there are some suggestions here
https://stackoverflow.com/questions/56718552/disable-gesture-to-pull-down-form-page-sheet-modal-presentation

**Comment by EyreFree** [comment]
@ebarellar 

Fixed in [5.2.2](https://github.com/EFPrefix/EFColorPicker/releases/tag/5.2.2).
