### ISSUE TITLE
有两个建议

### ISSUE THREAD

**Issue by hanks-hu** [EyreFree/EFColorPicker#30]
你好，首先这个库写的挺好，也挺实用，但是使用中有两个问题，用起来很不舒服。

### swift写的很冗余，好多地方的可以写的更简洁。

   1 、 比如 `EFColorSelectionViewController.swift`中，完全可以使用属性，就少写很多`as? EFColorSelectionView`
 ```
   func colorSelectionView() -> EFColorSelectionView {
        return self.view as? EFColorSelectionView ?? EFColorSelectionView()
    }
```
2、  很多冗余的类型。

-  ` let segmentControl: UISegmentedControl = UISegmentedControl(items: ["RGB", "HSB"] )` => ` let segmentControl = UISegmentedControl(items: ["RGB", "HSB"] )`
-  ` segmentControl.addTarget(...,for: UIControl.Event.valueChanged)` => ` segmentControl.addTarget(...,for: .valueChanged)`

**Comment by EyreFree** [comment]
@HanksHu 

感谢指点，求 PR...

![](https://user-images.githubusercontent.com/10757132/80119091-d361c500-85bb-11ea-9b61-56f348b00297.gif)

**Comment by evil7** [comment]
peeking someone finally diss ef's efcolorpick to give ef a color see see. Hahaha 🤡(efnb)
