### ISSUE TITLE
EFColorSelectionViewControllerDelegate not obj-c compatible.

### ISSUE THREAD

**Issue by nissaba** [EyreFree/EFColorPicker#4]
to make the EFColorSelectionViewControllerDelegate compatible with OBJC it needs to be set this way. 

```
@objc public protocol EFColorSelectionViewControllerDelegate: NSObjectProtocol {

    // Tells the data source to return the color components.
    // @param colorViewCntroller The color view.
    // @param color The new color value.
    func colorViewController(colorViewCntroller: EFColorSelectionViewController, didChangeColor color: UIColor)
}
```

**Comment by EyreFree** [comment]
Yes, `EFColorPicker` only works with Swift project now, and my Objective-C is not very proficient because I don't often use Objective-C. If it is convenient, can you make a PR to support Objective-C?

**Comment by nissaba** [comment]
I created a pull request with the modification I needed to do to have it work with OBJC.

**Comment by EyreFree** [comment]
The [PR](https://github.com/EyreFree/EFColorPicker/pull/6) has been merged, thanks for your work!
