### ISSUE TITLE
color wheel does not update to brightness

### ISSUE THREAD

**Issue by nissaba** [EyreFree/EFColorPicker#5]
The color wheel does not update its colors when the brightness slider is moved.

**Comment by EyreFree** [comment]
The brightness slider works well in demo project, can you provide more details?

**Comment by nissaba** [comment]
if you move the brightness slider the color picker is not updated, only the current color is. 
![simulator screen shot - iphone se - 2018-02-26 at 13 22 47](https://user-images.githubusercontent.com/3584506/36687752-804b5d02-1af8-11e8-99d8-b58c37246f35.png)
![simulator screen shot - iphone se - 2018-02-26 at 13 22 54](https://user-images.githubusercontent.com/3584506/36687753-805586ba-1af8-11e8-9199-c35a6dcb1b60.png)
![simulator screen shot - iphone se - 2018-02-26 at 13 22 58](https://user-images.githubusercontent.com/3584506/36687754-809b6860-1af8-11e8-9316-18ca7938b39c.png)

in the 3 images the color selection disk/circle is alway the same. 
normaly in other tools this would update to become fully black if the brightness slider is set to 0
and as the brightness increases the colors in the picker disk would get brighter as it goes up the scale. 

as can bee seen in the following images example from XCode color picker.
![capture d ecran 2018-02-26 a 13 29 29](https://user-images.githubusercontent.com/3584506/36688205-af753ade-1af9-11e8-84dc-78d9430e4cf3.png)
![capture d ecran 2018-02-26 a 13 29 38](https://user-images.githubusercontent.com/3584506/36688206-af7f37dc-1af9-11e8-8137-76fe80831bb0.png)
![capture d ecran 2018-02-26 a 13 29 44](https://user-images.githubusercontent.com/3584506/36688207-af90b17e-1af9-11e8-8bdd-8d199fc6bc10.png)

**Comment by nissaba** [comment]
Sorry for the UGE image size.

**Comment by nissaba** [comment]
Hi. I finally noticed that in HSB the brightness bar changes as you move the small selector disk. and this is where you know the outcome of the color with adjust brightness will be. The Slider bar is ever so thin it is hard to see and I did not noticed until today that it was chaging as I was moving the selector in the color wheel. 

So 1 suggestion is to make that bar thiker, so people that are presbyopic (like me) can notice the change. I did ask my graphic desinger to play with it, he also did not notieced that the sliderbar was chainging color and he as good eyesight. 

An other solution is to keep the slider bar on a black to withe gradiant and have the colorwheel update its colormap base on the brightness. 

I have updated my fork, as you change the brightness the color map updates.

**Comment by EyreFree** [comment]
Thanks for your contributions. Your PR has been merged.

You are the first user I know to actually use this library. Are you interested in being a collaborator of this project? In this way, you will be more convenient for the modification and development of this project. 

I sent you a invitation, click the link to see: [https://github.com/EyreFree/EFColorPicker/invitations](https://github.com/EyreFree/EFColorPicker/invitations).

😀

**Comment by nissaba** [comment]
Thanks. I have accepted it.
