### ISSUE TITLE
How to get the Hex Color Value or the Rgb Value

### ISSUE THREAD

**Issue by jelordreygulle** [EyreFree/EFColorPicker#8]
Can we be able to log og print the equivalent hex color value or the rgb value of the color ? for example how we will get the color value of  self.view.backgroundColor = color -> this color can we get the hex or the rgb equivalent?

**Comment by nissaba** [comment]
personally I use this when I know the hex of the color I want or need to hex string from a color I just use this extension https://gist.github.com/yannickl/16f0ed38f0698d9a8ae7  adding this to the interface ? I am not sure personally.

**Comment by EyreFree** [comment]
@jelordreygulle 

You should implement EFColorSelectionViewControllerDelegate so you can sense the color changes, and you can get the `UIColor` here:

```swift
// MARK:- EFColorSelectionViewControllerDelegate
func colorViewController(colorViewCntroller: EFColorSelectionViewController, didChangeColor color: UIColor) {
    self.view.backgroundColor = color

    // TODO: You can do something here when color changed.
    print("New color: " + color.debugDescription)
}
```

If you want RGB, see [https://stackoverflow.com/questions/437113/how-to-get-rgb-values-from-uicolor](https://stackoverflow.com/questions/437113/how-to-get-rgb-values-from-uicolor).
