### ISSUE TITLE
Crash in EFColorUtils.swift line 213

### ISSUE THREAD

**Issue by nissaba** [EyreFree/EFColorPicker#9]
Hello we noticed a crash in file EFColorUtils.swift at line 231  "UInt64(blue * EFRGBColorComponentMaxValue),"

I noticed while on an exception breakpoint that for some reason the blue value comes out negative. 
Tis so fare only happens with the blue color component. The crash I was able to break on the blue value vas at -0.00574635...

Will try to find out more. 

crash log
Crashed: com.apple.main-thread
0  MLS-Touch                      0x1052d9c84 specialized EFHexStringFromColor(color : UIColor) -> String? (EFColorUtils.swift:213)
1  MLS-Touch                      0x1053756a8 EFHSBView.reloadData() -> () (EFHSBView.swift:72)
2  MLS-Touch                      0x105376f04 EFHSBViewMLS_TouchEFColorView (EFHSBView.swift:56)
3  MLS-Touch                      0x1051384c4 specialized EFColorSelectionView.color (EFColorSelectionView.swift:51)
4  MLS-Touch                      0x1051381a0 EFColorSelectionView.colorView(colorView : EFColorView, didChangeColor : UIColor) -> () (EFColorSelectionView.swift)
5  MLS-Touch                      0x105377d64 specialized EFHSBView.ef_colorDidChangeValue(sender : EFColorWheelView) -> () (EFHSBView.swift:231)
6  MLS-Touch                      0x105376cf8 @objc EFHSBView.ef_colorDidChangeValue(sender : EFColorWheelView) -> () + 4313509112
7  UIKit                          0x18e60164c -[UIApplication sendAction:to:from:forEvent:] + 96
8  UIKit                          0x18e722870 -[UIControl sendAction:to:forEvent:] + 80
9  UIKit                          0x18e607700 -[UIControl _sendActionsForEvents:withEvent:] + 440
10 MLS-Touch                      0x10538a4fc specialized EFColorWheelView.onTouchEventWithPosition(point : CGPoint) -> () (EFColorWheelView.swift:126)
11 MLS-Touch                      0x105389ad0 @objc EFColorWheelView.touchesEnded(Set<UITouch>, with : UIEvent?) -> () (EFColorWheelView.swift)
12 UIKit                          0x18e68485c -[UIWindow _sendTouchesForEvent:] + 2040
13 UIKit                          0x18e679890 -[UIWindow sendEvent:] + 3160
14 UIKit                          0x18e6781d0 -[UIApplication sendEvent:] + 340
15 UIKit                          0x1a48d762c -[UIApplicationAccessibility sendEvent:] + 100
16 UIKit                          0x18ee59d1c __dispatchPreprocessedEventFromEventQueue + 2340
17 UIKit                          0x18ee5c2c8 __handleEventQueueInternal + 4744
18 UIKit                          0x18ee55368 __handleHIDEventFetcherDrain + 152
19 CoreFoundation                 0x18483b404 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
20 CoreFoundation                 0x18483ac2c __CFRunLoopDoSources0 + 276
21 CoreFoundation                 0x18483879c __CFRunLoopRun + 1204
22 CoreFoundation                 0x184758da8 CFRunLoopRunSpecific + 552
23 GraphicsServices               0x18673e020 GSEventRunModal + 100
24 UIKit                          0x18e778758 UIApplicationMain + 236
25 MLS-Touch                      0x104f48b1c main (main.m:33)
26 libdyld.dylib                  0x1841e9fc0 start + 4

**Comment by nissaba** [comment]
here is a print of the color components 
  - 0 : 0.605099296611869
  - 1 : 0.890196084976196
  - 2 : -0.00260558579605357
  - 3 : 1.0

Printing description of position:
▿ (198.5, 331.5)
  - x : 198.5
  - y : 331.5

<img width="385" alt="capture d ecran 2018-08-01 a 14 03 46" src="https://user-images.githubusercontent.com/3584506/43539755-c686514e-9593-11e8-89fb-816327ecd69b.png">

it really looks like this hapens a bit before the separation between the green and red section in the on the color wheel where the blue value should near total 0.

**Comment by nissaba** [comment]
![screen shot 2018-08-01 at 14 04 36](https://user-images.githubusercontent.com/3584506/43539869-21665a14-9594-11e8-8784-73c633254e35.png)

**Comment by EyreFree** [comment]
Fixed in [1.1.1](https://github.com/EyreFree/EFColorPicker/releases/tag/1.1.1).

@nissaba @illaz
